FROM jenkinsci/blueocean:1.19.0
COPY plugins-blueocean.txt /usr/share/jenkins/ref/plugins.txt
COPY user.groovy /usr/share/jenkins/ref/init.groovy.d/user.groovy
RUN /usr/local/bin/install-plugins.sh < /usr/share/jenkins/ref/plugins.txt