version: '3.7'
services:
  dind:
    image: docker:dind
    privileged: true
    networks:
      jenkins:
        aliases:
        - docker
    expose:
    - "2376"
    environment:
    - DOCKER_TLS_CERTDIR=/certs
    volumes:
    - type: volume
      source: jenkins-home
      target: /var/jenkins_home  
    - type: volume
      source: jenkins-docker-certs
      target: /certs/client
  
  jcac:
    image: nginx:latest
    volumes:
    - type: bind
      source: ./jcac.yml
      target: /usr/share/nginx/html/jcac.yml
    networks:
    - jenkins

  jenkins:
    build: .
    ports:
    - "8080:8080"
    - "50000:50000"
    environment:
    - DOCKER_HOST=tcp://docker:2376
    - DOCKER_CERT_PATH=/certs/client
    - DOCKER_TLS_VERIFY=1
    - JAVA_OPTS="-Djenkins.install.runSetupWizard=false"
    - CASC_JENKINS_CONFIG=http://jcac/jcac.yml
    - GITHUB_ACCESS_TOKEN=${GITHUB_ACCESS_TOKEN:-fake}
    - GITHUB_USERNAME=${GITHUB_USERNAME:-fake}
    volumes:
    - type: volume
      source: jenkins-home
      target: /var/jenkins_home
    - type: volume
      source: jenkins-docker-certs
      target: /certs/client
      read_only: true
    networks:
    - jenkins
volumes:
  jenkins-home:
  jenkins-docker-certs:
networks:
  jenkins:
