---
version: '3.7'
services:
  vault:
    image: vault:1.5.0
    restart: always
    cap_add:
    - IPC_LOCK
    ports:
    - "8200:8200"
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: my_very_secret_token